import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import { StoreProvider } from '~/lib/redux/store.provider';
import HeaderBar from '~/module/header/headerBar.component';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Ma présence',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <AntdRegistry>
                <html lang="en" suppressHydrationWarning>
                    <body className={inter.className}>
                        <div className="h-screen">
                            <div className="mb-10 relative w-screen">
                                <HeaderBar />
                            </div>
                            <div className="relative w-screen h-[80%]">{children}</div>
                        </div>
                        <Toaster position="bottom-right" richColors />
                    </body>
                </html>
            </AntdRegistry>
        </StoreProvider>
    );
}
